import pandas as pd

In [2]:
# We will convert json data into pandas dataframe

# Woking with JSON

pd.read_json('train.json') #loading dataset and converting into pandas dataframe

In [16]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR') #extracting json dataset through url

,api_url,api_docs,api_terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.050110
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.051777
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.426475
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,7.270000
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.024424
...,...,...,...,...,...,...,...
XOF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,7.637893
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.389489
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,3.411028
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.204121
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.301281

# Working with SQL

In [17]:
!pip install mysql.connector #to connect mysql with python

Processing c:\users\91842\appdata\local\pip\cache\wheels\57\e4\98\5feafb5c393dd2540e44b064a6f95832990d543e5b4f53ea8f\mysql_connector-2.2.9-cp38-cp38-win_amd64.whl
Installing collected packages: mysql.connector
Successfully installed mysql.connector

In [18]:
import mysql.connector

In [20]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world'),database name#machine ,user name,password

In [27]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)#sql query+conn variable

In [28]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]